# Generated by Django 5.0.2 on 2024-02-12 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateCreated", models.DateTimeField(auto_now_add=True, null=True)),
                ("dateModified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                        null=True,
                    ),
                ),
                ("isInActive", models.BooleanField(default=False)),
                ("isInActiveDate", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateCreated", models.DateTimeField(auto_now_add=True, null=True)),
                ("dateModified", models.DateTimeField(auto_now=True, null=True)),
                ("sku_code", models.CharField(blank=True, max_length=50, null=True)),
                ("item_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                        null=True,
                    ),
                ),
                ("tags", models.JSONField(blank=True, null=True)),
                ("in_stock", models.IntegerField(blank=True, null=True)),
                ("available_stock", models.IntegerField(blank=True, null=True)),
                ("units", models.CharField(blank=True, max_length=100, null=True)),
                ("minimum_stock", models.IntegerField(blank=True, null=True)),
                ("desired_stock", models.IntegerField(blank=True, null=True)),
                ("cost", models.FloatField(blank=True, null=True)),
                ("assembly_flag", models.BooleanField(default=False)),
                ("purchaseable_flag", models.BooleanField(default=False)),
                ("component_flag", models.BooleanField(default=False)),
                ("salable_flag", models.BooleanField(default=False)),
                ("bundle_flag", models.BooleanField(default=False)),
                ("isInActive", models.BooleanField(default=False)),
                ("isInActiveDate", models.DateTimeField(blank=True, null=True)),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateCreated", models.DateTimeField(auto_now_add=True, null=True)),
                ("dateModified", models.DateTimeField(auto_now=True, null=True)),
                ("firstName", models.CharField(blank=True, max_length=100, null=True)),
                ("lastName", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("N", "Non-binary")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "userType",
                    models.CharField(
                        blank=True,
                        choices=[("u1", "user1"), ("u2", "user2")],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "email_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("isInActive", models.BooleanField(default=False)),
                ("isInActiveDate", models.DateTimeField(blank=True, null=True)),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
